"""initial migration

Revision ID: 1f31286d7e7b
Revises: 
Create Date: 2024-05-30 01:09:59.879341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f31286d7e7b'  # миграция которая сейчас сгенирировалась
down_revision: Union[str, None] = None  # предидущая миграция, стоит не хеш, т.к. ее еще не было
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# функция говорит, что будет когда применим, пока создалась пустая база
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=5), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firstname'),
    sa.UniqueConstraint('lastname')
    )
    # ### end Alembic commands ###


# функция которая говорит что будет если отменим миграцию
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('faculty')
    # ### end Alembic commands ###
