"""initial migration

Revision ID: 477ced5f9889
Revises: 1f31286d7e7b
Create Date: 2024-05-30 01:25:57.012989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477ced5f9889'
down_revision: Union[str, None] = '1f31286d7e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('decan', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'faculty', ['decan'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculty', type_='unique')
    op.drop_column('faculty', 'decan')
    # ### end Alembic commands ###
